use clap::Parser;

use crate::commands;

#[derive(Parser, Debug)]
#[command(
    name = "jig",
    about = "Git worktree manager for parallel Claude Code sessions",
    version,
    after_help = "Use 'jig <command> --help' for more information about a command."
)]
pub struct Cli {
    /// Open/cd into worktree after creating
    #[arg(short = 'o', global = true)]
    pub open: bool,

    /// Skip on-create hook execution
    #[arg(long = "no-hooks", global = true)]
    pub no_hooks: bool,

    #[command(subcommand)]
    pub command: Option<Command>,
}

// Command enum generated by macro - doc comments come from Args structs
crate::command_enum! {
    #[command(visible_alias = "c")]
    (Create, commands::Create),

    #[command(visible_alias = "ls")]
    (List, commands::List),

    #[command(visible_alias = "o")]
    (Open, commands::Open),

    #[command(visible_alias = "rm")]
    (Remove, commands::Remove),

    (Exit, commands::Exit),
    (Config, commands::Config),
    (Spawn, commands::Spawn),
    (Ps, commands::Ps),
    (Attach, commands::Attach),
    (Review, commands::Review),
    (Merge, commands::Merge),
    (Kill, commands::Kill),
    (Init, commands::Init),
    (Update, commands::Update),
    (Version, commands::Version),
    (Which, commands::Which),
    (Health, commands::Health),
    (Status, commands::Status),

    #[command(name = "shell-init")]
    (ShellInit, commands::ShellInit),

    #[command(name = "shell-setup")]
    (ShellSetup, commands::ShellSetup),
}
